GET http://localhost:8080/users/1
###

GET http://localhost:8080/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlkIjoxLCJhIjpbIlNVUEVSX0FETUlOIl0sImV4cCI6MTczMTU2Nzc5Mn0.a580feyGi0YbISdarA9Xp7qA4uSN5rR0RaN8NnjULuY
###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}
###