GET http://localhost:8080/users/1
###

GET http://localhost:8080/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlkIjoxLCJhIjpbIkFETUlOIl0sImV4cCI6MTcyODgyMTcyNH0.ssyWciJ1S1J7a-1od761PArLbOT6yeD2b_7lZgtF4cA
###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###