GET http://localhost:8080/users/1
###

GET http://localhost:8080/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlkIjoxLCJhIjpbIlNVUEVSX0FETUlOIl0sImV4cCI6MTczMTU2Nzc5Mn0.a580feyGi0YbISdarA9Xp7qA4uSN5rR0RaN8NnjULuY
###

GET http://localhost:8080/documents/1/transitions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlkIjoxLCJhIjpbIkFETUlOIl0sImV4cCI6MTczMTc1MjU5NX0.gBpibWAnpK9eRxrR0jbaH-eXWWmYFfD9UB3WSeySD9I
###
POST http://172.18.27.101:8080//auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}
###