name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - "5432:5432"

      minio:
        image: quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z
        volumes:
          - ./data:/data
        ports:
          - "9000:9000"
          - "9001:9001"
        env:
          MINIO_ROOT_USER: 'minioadmin'
          MINIO_ROOT_PASSWORD: 'minioadmin'
          MINIO_ADDRESS: ':9000'
          MINIO_CONSOLE_ADDRESS: ':9001'

      elasticsearch:
        image: elasticsearch:8.10.1
        env:
          discovery.type: "single-node"
          ELASTIC_PASSWORD: "F8x6X_xkjA105DiuWTxC"
          http.port: "10200"
          transport.port: "10300"
          xpack.security.enabled: "false"
          xpack.security.transport.ssl.enabled: "false"
          xpack.security.http.ssl.enabled: "false"
        ports:
          - "10200:10200"
          - "10300:10300"

      zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
          - "2181:2181"
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: wurstmeister/kafka:latest
        ports:
          - "9092:9092"
          - "9093:9093"
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
          KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml