name: Java CD with Docker

on:
  push:
    branches: [ "main", "feature/38-cd" ]
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p 2231 digital.mephi.ru >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -v -p 2231 ubuntu@digital.mephi.ru "sudo -i && cd /home/ubuntu/eDocHub/ && docker-compose pull && docker-compose up -d"
